## Broadcasting

In [1]:
import numpy as np

In [2]:
np.array([1,2,3]) +0.5

array([1.5, 2.5, 3.5])

## Compatibility

Not every array is compatible.<br>
We check the last dimension of each array - a dimension is compatible if they are equal or either of them is 1.<br>
If all of A's dimensions are compatible with B's dimensions, or vice versa they are compatible.

In [4]:
np.random.seed(1234)
A = np.random.randint(low = 1, high = 10, size = (3,4))
B = np.random.randint(low = 1, high = 10, size = (3, 1))

In [5]:
print(A)
print(B)

[[4 7 6 5]
 [9 2 8 7]
 [9 1 6 1]]
[[7]
 [3]
 [1]]


In [6]:
print(A.shape)
print(B.shape)

(3, 4)
(3, 1)


## np.newaxis

This allows us to promote the dimensionality of an array by giving it a new axis.

In [9]:
A = np.array([3,11,4,5])
B = np.array([5,0,3])

If your goal is to build a difference matrix, i.e. substract each element of B from each element of A.<br>
You cannot do A - B as they are not compatible shapes and even if they were NumPy would do a element wise substraction.<br>

However, if A was 4x1 and B was a 1x3 array, numpy would broadcast the arrays so that A - B would produce matrix we desire.

In [10]:
# Convert A from (4, ) to (4, 1) array
A[:, np.newaxis]

array([[ 3],
       [11],
       [ 4],
       [ 5]])

In [11]:
# Convert B from (3, ) to (1, 3) array
B[np.newaxis, :]

array([[5, 0, 3]])

In [12]:
A[:, np.newaxis] - B[np.newaxis, :]

array([[-2,  3,  0],
       [ 6, 11,  8],
       [-1,  4,  1],
       [ 0,  5,  2]])

This can be further simplified, since broadcasting rules will make B compatible with our new A

In [13]:
A[:, np.newaxis] - B

array([[-2,  3,  0],
       [ 6, 11,  8],
       [-1,  4,  1],
       [ 0,  5,  2]])

In [14]:
A[:, np.newaxis].shape

(4, 1)

In [15]:
B.shape

(3,)

In [19]:
x = np.array([3,11,4,5])
y = x.view(dtype=np.int16, type=np.matrix)
y

matrix([[ 3,  0, 11,  0,  4,  0,  5,  0]], dtype=int16)

In [21]:
np.array(
    [
    [ ['a', 'b'], ['c', 'd'], ['e', 'f'] ],
    [ ['g', 'h'], ['i', 'j'], ['k', 'l'] ]
]
)

array([[['a', 'b'],
        ['c', 'd'],
        ['e', 'f']],

       [['g', 'h'],
        ['i', 'j'],
        ['k', 'l']]], dtype='<U1')

In [24]:
a = np.array([[1], [2], [3]])

In [25]:
a.shape

(3, 1)

## Reshape()

In [26]:
foo = np.arange(start=1, stop=9)
# [1 2 3 4 5 6 7 8]

In [27]:
# Change foo into 2x4 array

In [30]:
np.reshape(a=foo, newshape=(2,4))

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [31]:
foo.reshape(2,4)

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

## Array Transpose

In [34]:
bar = np.array([[1,2,3,4], [5,6,7,8]])

print(bar)
print(bar.shape)

[[1 2 3 4]
 [5 6 7 8]]
(2, 4)


In [35]:
print(bar.T)
print(bar.T.shape)

[[1 5]
 [2 6]
 [3 7]
 [4 8]]
(4, 2)


## Boolean Indexing

With this you can subset an array A using another array B of boolean values.

In [37]:
foo = np.array([
    [3, 9, 7],
    [2, 0, 3],
    [3, 3, 1]
])

In [40]:
mask = foo == 3
print(mask)

[[ True False False]
 [False False  True]
 [ True  True False]]


We can use mask to identify elemtns of food which are equal to 3.

In [41]:
print(foo[mask])

[3 3 3 3]


We can use mask to convert 3s into 0s

In [42]:
foo[mask] = 0

In [43]:
print(foo)

[[0 9 7]
 [2 0 0]
 [0 0 1]]


### Subset using 1D boolean array

In [48]:
foo = np.array([[3, 9, 7], 
                [2, 0, 3], 
                [3, 3, 1] ])

In [49]:
r13 = np.array([True, False, True])
c23 = np.array([False, True, True])

We use r13 to pull row 1 and 3

In [50]:
print(foo[r13])

[[3 9 7]
 [3 3 1]]


Same with c23 for row 2 and 3

In [51]:
print(foo[c23])

[[2 0 3]
 [3 3 1]]


**Combining both our boolean arrays**

In [52]:
print(foo[r13, c23])

[9 1]


r13 can be thought as indexing as [0,2]<br>
c23 can be thought as indexing as [1,2]<br>

When we combine row and column index arrays such as foo[[0,2] , [1,2]], NumPy will use correspinding indexes from each index array to select elements from target array, as such<br>
Selecting element (0,1)>9 and (2,2)>1

## Logical Operators

These let us combine boolean arrays, they include bitwise-and operator, the bitewise-or, and the bitwise-xor operator

In [54]:
b1 = np.array([False, False, True, True])
b2 = np.array([False, True, False, True])

print(b1 & b2)  # [False, False, False,  True], and
print(b1 | b2)  # [False,  True,  True,  True], or
print(b1 ^ b2)  # [False,  True,  True, False], xor

[False False False  True]
[False  True  True  True]
[False  True  True False]


**Boolean Negation**

We can negate a boolean array by preceding it with a tilde ~

In [55]:
~np.array([False,True])

array([ True, False])

## NaN

You can use NaN to represent missing values 